---
title: "Graficos tiempo hasta el alta"
author: "Carlos Martin Perez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r , echo=FALSE, warning=FALSE,comment=F,include=FALSE}

library(dplyr)
library(knitr)
library(gridExtra)
library(openintro)
library(formattable)
library(MASS)
library(ggplot2)
library(readxl)
library(pillar)
library(kableExtra)
library(lubridate)
library(segmented)
library(xtable)
library(ggpubr)
```  

```{r , echo=FALSE, warning=FALSE,include=FALSE}
library(lubridate)

neumonia<-read_excel("/Users/carlosmartinperez/Desktop/NEUMONIAS/BUENA/novedades/plantilla buena.xlsx",sheet=1)


emp<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_empirico)))
emp<-ifelse(emp<0,0,emp)
emp<-round(emp/3600,1)

neumonia$emp<-emp


recepcion<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_recepcion)))
recepcion<-ifelse(recepcion<0,0,recepcion)
recepcion<-round(recepcion/3600,1)
neumonia$recepcion<-recepcion


rapida<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_rapido)))
rapida<-ifelse(rapida<0,0,rapida)
rapida<-round(rapida/3600,1)
neumonia$rapida<-rapida 

rapida_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_rapido)))
rapida_cruda<-ifelse(rapida<0,0,rapida_cruda)
rapida_cruda<-round(rapida_cruda/3600,1)
neumonia$rapida_cruda<-rapida_cruda


diagetiol<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$fecha_diag_etiol_verdad)))
diagetiol<-ifelse(diagetiol<0,0,diagetiol)
diagetiol<-round(diagetiol/3600,1)
neumonia$diagetiol<-diagetiol

diagetiol_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$fecha_diag_etiol_verdad)))
diagetiol_cruda<-ifelse(diagetiol_cruda<0,0,diagetiol_cruda)
diagetiol_cruda<-round(diagetiol_cruda/3600,1)
neumonia$diagetiol_cruda<-diagetiol_cruda
 

diagetiol2<-as.duration(as.period(interval(neumonia$Fecha_h_rapido , neumonia$fecha_diag_etiol_verdad)))
diagetiol2<-ifelse(diagetiol2<0,0,diagetiol2)
diagetiol2<-round(diagetiol2/3600,1)
neumonia$diagetiol2<-diagetiol2
 


final<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_resultado_final)))
final<-ifelse(final<0,0,final)
final<-round(final/3600,1)
neumonia$final<-final  

final_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_resultado_final)))
final_cruda<-ifelse(final_cruda<0,0,final_cruda)
final_cruda<-round(final_cruda/3600,1)
neumonia$final_cruda<-final_cruda


alta<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_alta)))
alta<-ifelse(alta<0,0,alta)
alta<-round(alta/3600,1)
neumonia$alta<-alta

alta_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_alta)))
alta_cruda<-ifelse(alta_cruda<0,0,alta_cruda)
alta_cruda<-round(alta_cruda/3600,1)
neumonia$alta_cruda<-alta_cruda


provi<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_provi)))
provi<-ifelse(provi<0,0,provi)
provi<-round(provi/3600,1)
neumonia$provi<-provi  

provi_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_provi)))
provi_cruda<-ifelse(provi_cruda<0,0,provi_cruda)
provi_cruda<-round(provi_cruda/3600,1)
neumonia$provi_cruda<-provi_cruda


cambiodat<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_cambio)))
cambiodat<-ifelse(cambiodat<0,0,cambiodat)
cambiodat<-round(cambiodat/3600,1)
neumonia$cambiodat<-cambiodat

cambiodat_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_cambio)))
cambiodat_cruda<-ifelse(cambiodat_cruda<0,0,cambiodat_cruda)
cambiodat_cruda<-round(cambiodat_cruda/3600,1)
neumonia$cambiodat_cruda<-cambiodat_cruda

neumonia<-mutate(neumonia,cambiodat24=cambiodat/24,
           provi24=provi/24,
           alta24=alta/24,
           final24=final/24,
           diagetiol24=diagetiol/24,
           diagetiol224=diagetiol2/24,
           rapida24=rapida/24,
           recepcion24=recepcion/24,
           emp24=emp/24)

sub_neumo<-dplyr::filter(neumonia, DE==1)
sub_neumo<-dplyr::filter(sub_neumo, Hongo==0)
```     

**DIAS DESDE DIAGNOSTICO AL ALTA **   

***Pacientes con neumonía bacteriana que sobreviven***

**Nube de puntos con línea de regresión**  



```{r , echo=FALSE, warning=FALSE, message=FALSE}  
sub_neumo<-dplyr::filter(sub_neumo,Muertos==0) 
sub_neumo<-mutate(sub_neumo,alta_cruda24=alta_cruda/24) 

nube<-ggplot(sub_neumo, aes(x = Periodo, y = alta_cruda24 )) +
  geom_point(color="black")+
  scale_x_continuous(breaks = c(1:max(neumonia$Periodo)))+
  #geom_line(color="grey70")+
  ggtitle("Días de estancia en hospital por periodo",subtitle = "Neumonías bacterianas")+
  theme_minimal()+
  labs(x='Periodo', y='Días hasta el alta')  
nube +geom_smooth(method = "lm")
```    

**Mediana de estancia en hospital por periodos**   

```{r , echo=FALSE, warning=FALSE, message=FALSE}  
grupo<-sub_neumo %>% group_by(Periodo)
gm_alta<-grupo %>% summarise( Mediana_dias = median(alta_cruda24,na.rm = T))
gm_alta<- na.omit(gm_alta)

p_alta<- ggplot(gm_alta, aes(x = Periodo, y = Mediana_dias )) +
  geom_point(color="black")+
  scale_x_continuous(breaks = c(1:max(neumonia$Periodo)))+
  geom_line(color="grey70")+
  ggtitle("Mediana dias de estancia en hospital por periodo",subtitle = "Neumonías bacterianas")+
  theme_minimal()+
  labs(x='Periodo', y='Mediana de días hasta el alta') 

p_alta  
```

***Pacientes con neumonía bacteriana que sobreviven o fallecen***  

```{r , echo=FALSE, warning=FALSE, message=FALSE}  
sub_neumo<-dplyr::filter(neumonia, DE==1)
sub_neumo<-dplyr::filter(sub_neumo, Hongo==0)
sub_neumo<-mutate(sub_neumo,alta_cruda24=alta_cruda/24) 

nube<-ggplot(sub_neumo, aes(x = Periodo, y = alta_cruda24 )) +
  geom_point(color="black")+
  scale_x_continuous(breaks = c(1:max(neumonia$Periodo)))+
  #geom_line(color="grey70")+
  ggtitle("Días de estancia en hospital por periodo",subtitle = "Neumonías bacterianas")+
  theme_minimal()+
  labs(x='Periodo', y='Días hasta el alta')  
nube +geom_smooth(method = "lm")
```  

***neumonías  con o sin diagnostico etiologico***    

```{r , echo=FALSE, warning=FALSE, message=FALSE}  

neumonia<-mutate(neumonia,alta_cruda24=alta_cruda/24) 

nube<-ggplot(neumonia, aes(x = Periodo, y = alta_cruda24 )) +
  geom_point(color="black")+
  scale_x_continuous(breaks = c(1:max(neumonia$Periodo)))+
  #geom_line(color="grey70")+
  ggtitle("Días de estancia en hospital por periodo",subtitle = "Neumonías bacterianas")+
  theme_minimal()+
  labs(x='Periodo', y='Días hasta el alta')  
nube +geom_smooth(method = "lm")
```  