---
title: "Resumen tabla tiempos neumonia"
author: "Carlos Martin Perez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r , echo=FALSE, warning=FALSE,comment=F,include=FALSE}

library(dplyr)
library(knitr)
library(gridExtra)
library(openintro)
library(formattable)
library(MASS)
library(ggplot2)
library(readxl)
library(pillar)
library(kableExtra)
library(lubridate)
library(segmented)
library(xtable)
library(ggpubr)
library(crosstable)
library(flextable)
```  


```{r , echo=FALSE, warning=FALSE,include=FALSE}
neumonia<-read_excel("/Users/carlosmartinperez/Desktop/NEUMONIAS/BUENA/novedades/plantilla buena.xlsx",sheet=1)

diagetiol<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$fecha_diag_etiol_verdad)))
diagetiol<-ifelse(diagetiol<0,0,diagetiol)
diagetiol<-round(diagetiol/3600,1)
neumonia$diagetiol<-diagetiol

final<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_resultado_final)))
final<-ifelse(final<0,0,final)
final<-round(final/3600,1)
neumonia$final<-final  

alta<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_alta)))
alta<-ifelse(alta<0,0,alta)
alta<-round(alta/3600,1)
neumonia$alta<-alta

alta_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_alta)))
alta_cruda<-ifelse(alta_cruda<0,0,alta_cruda)
alta_cruda<-round(alta_cruda/3600,1)
neumonia$alta_cruda<-alta_cruda


provi<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_h_provi)))
provi<-ifelse(provi<0,0,provi)
provi<-round(provi/3600,1)
neumonia$provi<-provi  

provi_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_h_provi)))
provi_cruda<-ifelse(provi_cruda<0,0,provi_cruda)
provi_cruda<-round(provi_cruda/3600,1)
neumonia$provi_cruda<-provi_cruda

cambiodat<-as.duration(as.period(interval(neumonia$Fecha_h_recepcion , neumonia$Fecha_cambio)))
cambiodat<-ifelse(cambiodat<0,0,cambiodat)
cambiodat<-round(cambiodat/3600,1)
neumonia$cambiodat<-cambiodat

cambiodat_cruda<-as.duration(as.period(interval(neumonia$Fecha_h_neumo , neumonia$Fecha_cambio)))
cambiodat_cruda<-ifelse(cambiodat_cruda<0,0,cambiodat_cruda)
cambiodat_cruda<-round(cambiodat_cruda/3600,1)
neumonia$cambiodat_cruda<-cambiodat_cruda

neumonia<-mutate(neumonia,cambiodat24=cambiodat/24,
           provi24=provi/24,
           alta24=alta/24,
           final24=final/24,
           diagetiol24=diagetiol/24,
           diagetiol224=diagetiol2/24,
           rapida24=rapida/24,
           recepcion24=recepcion/24,
           emp24=emp/24)

sub_neumo<-dplyr::filter(neumonia, DE==1)
sub_neumo<-dplyr::filter(sub_neumo, Hongo==0)  

neumo_labels=read.table(header=TRUE,text="name label
                        diagetiol 'recepción-> diag.etiologico'
                        final 'recepción-> I. final'
                        cambiodat 'recepción-> tto. dirigido'
                        alta_cruda 'diagnóstico-> alta'
                        alta 'recepción-> alta")
neumo2=sub_neumo%>%
  import_labels(neumo_labels, name_from="name", label_from="label") %>% 
  as_tibble()

neumo3=neumonia%>%
  import_labels(neumo_labels, name_from="name", label_from="label") %>% 
  as_tibble()

```     

### TABLA DE VARIABLES CON CAMBIOS SIGNIFICATIVOS PRE -POST
### BASE DE DATOS SIN HONGOS  

```{r , echo=FALSE, warning=FALSE,results='asis'}
crosstable(neumo2, c(alta,alta_cruda,final,diagetiol,cambiodat), by=Pre_post,test=TRUE) %>%
  as_flextable(keep_id=TRUE)

```    

### BASE DE DATOS CON HONGOS  

```{r , echo=FALSE, warning=FALSE,results='asis'}
crosstable(neumo3, c(alta,alta_cruda,final,diagetiol,cambiodat), by=Pre_post,test=TRUE) %>%
  as_flextable(keep_id=TRUE)
```    


